# Database Module - Ablage-System OCR
# PostgreSQL database VM

resource "proxmox_vm_qemu" "postgres" {
  name        = "${var.name_prefix}-postgres"
  target_node = "pve"  # Change to your Proxmox node name
  vmid        = 150

  # VM Configuration
  cores   = var.postgres_vm_cores
  sockets = 1
  memory  = var.postgres_vm_memory

  # Boot configuration
  boot    = "order=scsi0"
  agent   = 1
  onboot  = true

  # Disk configuration
  disk {
    slot    = 0
    size    = "${var.postgres_disk_size_gb}G"
    type    = "scsi"
    storage = "local-lvm"
    ssd     = 1
    discard = "on"
  }

  # Network configuration
  network {
    model  = "virtio"
    bridge = var.network_id
  }

  # Cloud-init configuration
  os_type   = "cloud-init"
  ipconfig0 = "ip=dhcp"

  # Lifecycle
  lifecycle {
    ignore_changes = [
      network,
    ]
  }

  tags = var.tags
}

# PostgreSQL configuration file
resource "local_file" "postgres_config" {
  filename = "${path.module}/postgresql.conf.template"

  content = <<-EOT
    # PostgreSQL Configuration - Ablage-System ${var.environment}
    # Auto-generated by Terraform

    # Connection Settings
    max_connections = ${var.postgres_max_connections}
    superuser_reserved_connections = 3

    # Memory Settings
    shared_buffers = ${var.postgres_shared_buffers}
    effective_cache_size = ${replace(var.postgres_shared_buffers, "GB", "")}GB
    work_mem = ${floor(replace(var.postgres_shared_buffers, "GB", "") * 1024 / var.postgres_max_connections)}MB
    maintenance_work_mem = ${floor(replace(var.postgres_shared_buffers, "GB", "") * 1024 / 16)}MB

    # Checkpoint Settings
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    min_wal_size = 1GB
    max_wal_size = 4GB

    # Query Planning
    random_page_cost = 1.1  # SSD
    effective_io_concurrency = 200  # SSD

    # Logging
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_truncate_on_rotation = off
    log_rotation_age = 1d
    log_rotation_size = 100MB
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    log_min_duration_statement = 1000  # Log queries > 1s

    # Autovacuum
    autovacuum = on
    autovacuum_max_workers = 3
    autovacuum_naptime = 1min

    # Performance Monitoring
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    pg_stat_statements.max = 10000

    # Replication (if needed)
    wal_level = replica
    max_wal_senders = 10
    hot_standby = on
  EOT
}

# Backup script
resource "local_file" "backup_script" {
  filename = "${path.module}/backup-postgres.sh"

  content = <<-EOT
    #!/bin/bash
    # PostgreSQL Backup Script - Ablage-System
    # Schedule: ${var.postgres_backup_schedule}

    set -e

    BACKUP_DIR="/mnt/backups/postgres"
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    RETENTION_DAYS=${var.postgres_backup_retention}

    # Create backup directory
    mkdir -p "$BACKUP_DIR"

    # Backup database
    pg_dump -U postgres -Fc ablage_system > "$BACKUP_DIR/ablage_system_$TIMESTAMP.dump"

    # Backup globals
    pg_dumpall -U postgres --globals-only > "$BACKUP_DIR/globals_$TIMESTAMP.sql"

    # Compress backups
    gzip "$BACKUP_DIR/globals_$TIMESTAMP.sql"

    # Clean old backups
    find "$BACKUP_DIR" -name "*.dump" -mtime +$RETENTION_DAYS -delete
    find "$BACKUP_DIR" -name "*.sql.gz" -mtime +$RETENTION_DAYS -delete

    echo "Backup completed: $TIMESTAMP"
  EOT

  file_permission = "0755"
}
