{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ablage-system.secretName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ablage-system.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  minio-access-key: {{ .Values.secrets.minioAccessKey | b64enc | quote }}
  minio-secret-key: {{ .Values.secrets.minioSecretKey | b64enc | quote }}
  app-secret-key: {{ .Values.secrets.appSecretKey | b64enc | quote }}
{{- end }}
