# Load Balancer Module - Ablage-System OCR
# Nginx load balancer VM

resource "proxmox_vm_qemu" "load_balancer" {
  name        = "${var.name_prefix}-lb"
  target_node = "pve"  # Change to your Proxmox node name
  vmid        = 100

  # VM Configuration
  cores   = var.lb_vm_cores
  sockets = 1
  memory  = var.lb_vm_memory

  # Boot configuration
  boot    = "order=scsi0"
  agent   = 1
  onboot  = true

  # Disk configuration
  disk {
    slot    = 0
    size    = "50G"
    type    = "scsi"
    storage = "local-lvm"
    ssd     = 1
    discard = "on"
  }

  # Network configuration
  network {
    model  = "virtio"
    bridge = var.network_id
  }

  # Cloud-init configuration
  os_type   = "cloud-init"
  ipconfig0 = "ip=dhcp"

  # Lifecycle
  lifecycle {
    ignore_changes = [
      network,
    ]
  }

  tags = var.tags
}

# Nginx configuration template
resource "local_file" "nginx_config" {
  filename = "${path.module}/nginx.conf.template"

  content = <<-EOT
    # Nginx Load Balancer Configuration - Ablage-System
    # Auto-generated by Terraform

    upstream backend_api {
      least_conn;
      ${join("\n  ", [for ip in var.backend_targets : "server ${ip}:8000 max_fails=3 fail_timeout=30s;"])}
    }

    # HTTP server (redirect to HTTPS)
    server {
      listen 80;
      server_name ${var.domain_name};

      location / {
        return 301 https://$server_name$request_uri;
      }
    }

    # HTTPS server
    server {
      listen 443 ssl http2;
      server_name ${var.domain_name};

      # SSL configuration
      ${var.enable_ssl ? "ssl_certificate ${var.ssl_cert_path};" : "# SSL disabled"}
      ${var.enable_ssl ? "ssl_certificate_key ${var.ssl_key_path};" : ""}
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_ciphers HIGH:!aNULL:!MD5;

      # Security headers
      add_header Strict-Transport-Security "max-age=31536000" always;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-Content-Type-Options "nosniff" always;

      # API proxy
      location /api/ {
        proxy_pass http://backend_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Health check
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
      }

      # Health check endpoint
      location ${var.health_check_path} {
        proxy_pass http://backend_api${var.health_check_path};
        access_log off;
      }
    }
  EOT
}

# Health check script
resource "local_file" "health_check" {
  filename = "${path.module}/health-check.sh"

  content = <<-EOT
    #!/bin/bash
    # Health Check Script for Load Balancer

    # Check backend health
    for backend in ${join(" ", var.backend_targets)}; do
      if curl -f -s "http://$backend:8000${var.health_check_path}" > /dev/null; then
        echo "✅ $backend is healthy"
      else
        echo "❌ $backend is unhealthy"
      fi
    done
  EOT

  file_permission = "0755"
}
