/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as ValidationQueueRouteImport } from './app/routes/validation-queue'
import { Route as UploadRouteImport } from './app/routes/upload'
import { Route as SearchRouteImport } from './app/routes/search'
import { Route as RelationshipsRouteImport } from './app/routes/relationships'
import { Route as MonitoringRouteImport } from './app/routes/monitoring'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as LieferantenRouteImport } from './app/routes/lieferanten'
import { Route as KundenRouteImport } from './app/routes/kunden'
import { Route as JobsRouteImport } from './app/routes/jobs'
import { Route as DocumentGroupsRouteImport } from './app/routes/document-groups'
import { Route as ChatRouteImport } from './app/routes/chat'
import { Route as BusinessEntitiesRouteImport } from './app/routes/business-entities'
import { Route as AutomationRouteImport } from './app/routes/automation'
import { Route as AdminRouteImport } from './app/routes/admin'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as LieferantenIndexRouteImport } from './app/routes/lieferanten.index'
import { Route as KundenIndexRouteImport } from './app/routes/kunden.index'
import { Route as AdminIndexRouteImport } from './app/routes/admin.index'
import { Route as ValidationQueueIdRouteImport } from './app/routes/validation-queue.$id'
import { Route as LieferantenSupplierIdRouteImport } from './app/routes/lieferanten.$supplierId'
import { Route as KundenCustomerIdRouteImport } from './app/routes/kunden.$customerId'
import { Route as DocumentsDocumentIdRouteImport } from './app/routes/documents.$documentId'
import { Route as DocumentGroupsIdRouteImport } from './app/routes/document-groups.$id'
import { Route as BusinessEntitiesIdRouteImport } from './app/routes/business-entities.$id'
import { Route as AdminUsersRouteImport } from './app/routes/admin.users'
import { Route as AdminTunesRouteImport } from './app/routes/admin.tunes'
import { Route as AdminSettingsRouteImport } from './app/routes/admin.settings'
import { Route as AdminOcrTrainingRouteImport } from './app/routes/admin.ocr-training'
import { Route as AdminOcrReviewRouteImport } from './app/routes/admin.ocr-review'
import { Route as AdminOcrBackendsRouteImport } from './app/routes/admin.ocr-backends'
import { Route as AdminDatevRouteImport } from './app/routes/admin.datev'
import { Route as AdminBankingRouteImport } from './app/routes/admin.banking'
import { Route as LieferantenSupplierIdIndexRouteImport } from './app/routes/lieferanten.$supplierId.index'
import { Route as KundenCustomerIdIndexRouteImport } from './app/routes/kunden.$customerId.index'
import { Route as AdminDatevIndexRouteImport } from './app/routes/admin.datev.index'
import { Route as AdminBankingIndexRouteImport } from './app/routes/admin.banking.index'
import { Route as LieferantenSupplierIdFolderIdRouteImport } from './app/routes/lieferanten.$supplierId.$folderId'
import { Route as KundenCustomerIdFolderIdRouteImport } from './app/routes/kunden.$customerId.$folderId'
import { Route as DocumentsDocumentIdRelationshipsRouteImport } from './app/routes/documents.$documentId.relationships'
import { Route as AdminOcrBackendsBackendRouteImport } from './app/routes/admin.ocr-backends.$backend'
import { Route as AdminDatevVendorsRouteImport } from './app/routes/admin.datev.vendors'
import { Route as AdminDatevHistoryRouteImport } from './app/routes/admin.datev.history'
import { Route as AdminDatevExportRouteImport } from './app/routes/admin.datev.export'
import { Route as AdminDatevConfigRouteImport } from './app/routes/admin.datev.config'
import { Route as AdminBankingTransactionsRouteImport } from './app/routes/admin.banking.transactions'
import { Route as AdminBankingSkontoRouteImport } from './app/routes/admin.banking.skonto'
import { Route as AdminBankingReconciliationRouteImport } from './app/routes/admin.banking.reconciliation'
import { Route as AdminBankingPaymentsRouteImport } from './app/routes/admin.banking.payments'
import { Route as AdminBankingImportRouteImport } from './app/routes/admin.banking.import'
import { Route as AdminBankingAccountsRouteImport } from './app/routes/admin.banking.accounts'
import { Route as LieferantenSupplierIdFolderIdCategoryRouteImport } from './app/routes/lieferanten.$supplierId.$folderId.$category'
import { Route as KundenCustomerIdFolderIdCategoryRouteImport } from './app/routes/kunden.$customerId.$folderId.$category'
import { Route as AdminOcrTrainingBatchIdRouteImport } from './app/routes/admin.ocr-training.batch.$id'

const ValidationQueueRoute = ValidationQueueRouteImport.update({
  id: '/validation-queue',
  path: '/validation-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LieferantenRoute = LieferantenRouteImport.update({
  id: '/lieferanten',
  path: '/lieferanten',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenRoute = KundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentGroupsRoute = DocumentGroupsRouteImport.update({
  id: '/document-groups',
  path: '/document-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessEntitiesRoute = BusinessEntitiesRouteImport.update({
  id: '/business-entities',
  path: '/business-entities',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LieferantenIndexRoute = LieferantenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LieferantenRoute,
} as any)
const KundenIndexRoute = KundenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KundenRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ValidationQueueIdRoute = ValidationQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ValidationQueueRoute,
} as any)
const LieferantenSupplierIdRoute = LieferantenSupplierIdRouteImport.update({
  id: '/$supplierId',
  path: '/$supplierId',
  getParentRoute: () => LieferantenRoute,
} as any)
const KundenCustomerIdRoute = KundenCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => KundenRoute,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentGroupsIdRoute = DocumentGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentGroupsRoute,
} as any)
const BusinessEntitiesIdRoute = BusinessEntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusinessEntitiesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTunesRoute = AdminTunesRouteImport.update({
  id: '/tunes',
  path: '/tunes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOcrTrainingRoute = AdminOcrTrainingRouteImport.update({
  id: '/ocr-training',
  path: '/ocr-training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOcrReviewRoute = AdminOcrReviewRouteImport.update({
  id: '/ocr-review',
  path: '/ocr-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOcrBackendsRoute = AdminOcrBackendsRouteImport.update({
  id: '/ocr-backends',
  path: '/ocr-backends',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatevRoute = AdminDatevRouteImport.update({
  id: '/datev',
  path: '/datev',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBankingRoute = AdminBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AdminRoute,
} as any)
const LieferantenSupplierIdIndexRoute =
  LieferantenSupplierIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LieferantenSupplierIdRoute,
  } as any)
const KundenCustomerIdIndexRoute = KundenCustomerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KundenCustomerIdRoute,
} as any)
const AdminDatevIndexRoute = AdminDatevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDatevRoute,
} as any)
const AdminBankingIndexRoute = AdminBankingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBankingRoute,
} as any)
const LieferantenSupplierIdFolderIdRoute =
  LieferantenSupplierIdFolderIdRouteImport.update({
    id: '/$folderId',
    path: '/$folderId',
    getParentRoute: () => LieferantenSupplierIdRoute,
  } as any)
const KundenCustomerIdFolderIdRoute =
  KundenCustomerIdFolderIdRouteImport.update({
    id: '/$folderId',
    path: '/$folderId',
    getParentRoute: () => KundenCustomerIdRoute,
  } as any)
const DocumentsDocumentIdRelationshipsRoute =
  DocumentsDocumentIdRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => DocumentsDocumentIdRoute,
  } as any)
const AdminOcrBackendsBackendRoute = AdminOcrBackendsBackendRouteImport.update({
  id: '/$backend',
  path: '/$backend',
  getParentRoute: () => AdminOcrBackendsRoute,
} as any)
const AdminDatevVendorsRoute = AdminDatevVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminDatevRoute,
} as any)
const AdminDatevHistoryRoute = AdminDatevHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminDatevRoute,
} as any)
const AdminDatevExportRoute = AdminDatevExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminDatevRoute,
} as any)
const AdminDatevConfigRoute = AdminDatevConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminDatevRoute,
} as any)
const AdminBankingTransactionsRoute =
  AdminBankingTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AdminBankingRoute,
  } as any)
const AdminBankingSkontoRoute = AdminBankingSkontoRouteImport.update({
  id: '/skonto',
  path: '/skonto',
  getParentRoute: () => AdminBankingRoute,
} as any)
const AdminBankingReconciliationRoute =
  AdminBankingReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AdminBankingRoute,
  } as any)
const AdminBankingPaymentsRoute = AdminBankingPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminBankingRoute,
} as any)
const AdminBankingImportRoute = AdminBankingImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminBankingRoute,
} as any)
const AdminBankingAccountsRoute = AdminBankingAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminBankingRoute,
} as any)
const LieferantenSupplierIdFolderIdCategoryRoute =
  LieferantenSupplierIdFolderIdCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => LieferantenSupplierIdFolderIdRoute,
  } as any)
const KundenCustomerIdFolderIdCategoryRoute =
  KundenCustomerIdFolderIdCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => KundenCustomerIdFolderIdRoute,
  } as any)
const AdminOcrTrainingBatchIdRoute = AdminOcrTrainingBatchIdRouteImport.update({
  id: '/batch/$id',
  path: '/batch/$id',
  getParentRoute: () => AdminOcrTrainingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/automation': typeof AutomationRoute
  '/business-entities': typeof BusinessEntitiesRouteWithChildren
  '/chat': typeof ChatRoute
  '/document-groups': typeof DocumentGroupsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/kunden': typeof KundenRouteWithChildren
  '/lieferanten': typeof LieferantenRouteWithChildren
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relationships': typeof RelationshipsRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/validation-queue': typeof ValidationQueueRouteWithChildren
  '/admin/banking': typeof AdminBankingRouteWithChildren
  '/admin/datev': typeof AdminDatevRouteWithChildren
  '/admin/ocr-backends': typeof AdminOcrBackendsRouteWithChildren
  '/admin/ocr-review': typeof AdminOcrReviewRoute
  '/admin/ocr-training': typeof AdminOcrTrainingRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tunes': typeof AdminTunesRoute
  '/admin/users': typeof AdminUsersRoute
  '/business-entities/$id': typeof BusinessEntitiesIdRoute
  '/document-groups/$id': typeof DocumentGroupsIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRouteWithChildren
  '/kunden/$customerId': typeof KundenCustomerIdRouteWithChildren
  '/lieferanten/$supplierId': typeof LieferantenSupplierIdRouteWithChildren
  '/validation-queue/$id': typeof ValidationQueueIdRoute
  '/admin/': typeof AdminIndexRoute
  '/kunden/': typeof KundenIndexRoute
  '/lieferanten/': typeof LieferantenIndexRoute
  '/admin/banking/accounts': typeof AdminBankingAccountsRoute
  '/admin/banking/import': typeof AdminBankingImportRoute
  '/admin/banking/payments': typeof AdminBankingPaymentsRoute
  '/admin/banking/reconciliation': typeof AdminBankingReconciliationRoute
  '/admin/banking/skonto': typeof AdminBankingSkontoRoute
  '/admin/banking/transactions': typeof AdminBankingTransactionsRoute
  '/admin/datev/config': typeof AdminDatevConfigRoute
  '/admin/datev/export': typeof AdminDatevExportRoute
  '/admin/datev/history': typeof AdminDatevHistoryRoute
  '/admin/datev/vendors': typeof AdminDatevVendorsRoute
  '/admin/ocr-backends/$backend': typeof AdminOcrBackendsBackendRoute
  '/documents/$documentId/relationships': typeof DocumentsDocumentIdRelationshipsRoute
  '/kunden/$customerId/$folderId': typeof KundenCustomerIdFolderIdRouteWithChildren
  '/lieferanten/$supplierId/$folderId': typeof LieferantenSupplierIdFolderIdRouteWithChildren
  '/admin/banking/': typeof AdminBankingIndexRoute
  '/admin/datev/': typeof AdminDatevIndexRoute
  '/kunden/$customerId/': typeof KundenCustomerIdIndexRoute
  '/lieferanten/$supplierId/': typeof LieferantenSupplierIdIndexRoute
  '/admin/ocr-training/batch/$id': typeof AdminOcrTrainingBatchIdRoute
  '/kunden/$customerId/$folderId/$category': typeof KundenCustomerIdFolderIdCategoryRoute
  '/lieferanten/$supplierId/$folderId/$category': typeof LieferantenSupplierIdFolderIdCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/business-entities': typeof BusinessEntitiesRouteWithChildren
  '/chat': typeof ChatRoute
  '/document-groups': typeof DocumentGroupsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relationships': typeof RelationshipsRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/validation-queue': typeof ValidationQueueRouteWithChildren
  '/admin/ocr-backends': typeof AdminOcrBackendsRouteWithChildren
  '/admin/ocr-review': typeof AdminOcrReviewRoute
  '/admin/ocr-training': typeof AdminOcrTrainingRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tunes': typeof AdminTunesRoute
  '/admin/users': typeof AdminUsersRoute
  '/business-entities/$id': typeof BusinessEntitiesIdRoute
  '/document-groups/$id': typeof DocumentGroupsIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRouteWithChildren
  '/validation-queue/$id': typeof ValidationQueueIdRoute
  '/admin': typeof AdminIndexRoute
  '/kunden': typeof KundenIndexRoute
  '/lieferanten': typeof LieferantenIndexRoute
  '/admin/banking/accounts': typeof AdminBankingAccountsRoute
  '/admin/banking/import': typeof AdminBankingImportRoute
  '/admin/banking/payments': typeof AdminBankingPaymentsRoute
  '/admin/banking/reconciliation': typeof AdminBankingReconciliationRoute
  '/admin/banking/skonto': typeof AdminBankingSkontoRoute
  '/admin/banking/transactions': typeof AdminBankingTransactionsRoute
  '/admin/datev/config': typeof AdminDatevConfigRoute
  '/admin/datev/export': typeof AdminDatevExportRoute
  '/admin/datev/history': typeof AdminDatevHistoryRoute
  '/admin/datev/vendors': typeof AdminDatevVendorsRoute
  '/admin/ocr-backends/$backend': typeof AdminOcrBackendsBackendRoute
  '/documents/$documentId/relationships': typeof DocumentsDocumentIdRelationshipsRoute
  '/kunden/$customerId/$folderId': typeof KundenCustomerIdFolderIdRouteWithChildren
  '/lieferanten/$supplierId/$folderId': typeof LieferantenSupplierIdFolderIdRouteWithChildren
  '/admin/banking': typeof AdminBankingIndexRoute
  '/admin/datev': typeof AdminDatevIndexRoute
  '/kunden/$customerId': typeof KundenCustomerIdIndexRoute
  '/lieferanten/$supplierId': typeof LieferantenSupplierIdIndexRoute
  '/admin/ocr-training/batch/$id': typeof AdminOcrTrainingBatchIdRoute
  '/kunden/$customerId/$folderId/$category': typeof KundenCustomerIdFolderIdCategoryRoute
  '/lieferanten/$supplierId/$folderId/$category': typeof LieferantenSupplierIdFolderIdCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/automation': typeof AutomationRoute
  '/business-entities': typeof BusinessEntitiesRouteWithChildren
  '/chat': typeof ChatRoute
  '/document-groups': typeof DocumentGroupsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/kunden': typeof KundenRouteWithChildren
  '/lieferanten': typeof LieferantenRouteWithChildren
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relationships': typeof RelationshipsRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/validation-queue': typeof ValidationQueueRouteWithChildren
  '/admin/banking': typeof AdminBankingRouteWithChildren
  '/admin/datev': typeof AdminDatevRouteWithChildren
  '/admin/ocr-backends': typeof AdminOcrBackendsRouteWithChildren
  '/admin/ocr-review': typeof AdminOcrReviewRoute
  '/admin/ocr-training': typeof AdminOcrTrainingRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tunes': typeof AdminTunesRoute
  '/admin/users': typeof AdminUsersRoute
  '/business-entities/$id': typeof BusinessEntitiesIdRoute
  '/document-groups/$id': typeof DocumentGroupsIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRouteWithChildren
  '/kunden/$customerId': typeof KundenCustomerIdRouteWithChildren
  '/lieferanten/$supplierId': typeof LieferantenSupplierIdRouteWithChildren
  '/validation-queue/$id': typeof ValidationQueueIdRoute
  '/admin/': typeof AdminIndexRoute
  '/kunden/': typeof KundenIndexRoute
  '/lieferanten/': typeof LieferantenIndexRoute
  '/admin/banking/accounts': typeof AdminBankingAccountsRoute
  '/admin/banking/import': typeof AdminBankingImportRoute
  '/admin/banking/payments': typeof AdminBankingPaymentsRoute
  '/admin/banking/reconciliation': typeof AdminBankingReconciliationRoute
  '/admin/banking/skonto': typeof AdminBankingSkontoRoute
  '/admin/banking/transactions': typeof AdminBankingTransactionsRoute
  '/admin/datev/config': typeof AdminDatevConfigRoute
  '/admin/datev/export': typeof AdminDatevExportRoute
  '/admin/datev/history': typeof AdminDatevHistoryRoute
  '/admin/datev/vendors': typeof AdminDatevVendorsRoute
  '/admin/ocr-backends/$backend': typeof AdminOcrBackendsBackendRoute
  '/documents/$documentId/relationships': typeof DocumentsDocumentIdRelationshipsRoute
  '/kunden/$customerId/$folderId': typeof KundenCustomerIdFolderIdRouteWithChildren
  '/lieferanten/$supplierId/$folderId': typeof LieferantenSupplierIdFolderIdRouteWithChildren
  '/admin/banking/': typeof AdminBankingIndexRoute
  '/admin/datev/': typeof AdminDatevIndexRoute
  '/kunden/$customerId/': typeof KundenCustomerIdIndexRoute
  '/lieferanten/$supplierId/': typeof LieferantenSupplierIdIndexRoute
  '/admin/ocr-training/batch/$id': typeof AdminOcrTrainingBatchIdRoute
  '/kunden/$customerId/$folderId/$category': typeof KundenCustomerIdFolderIdCategoryRoute
  '/lieferanten/$supplierId/$folderId/$category': typeof LieferantenSupplierIdFolderIdCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/automation'
    | '/business-entities'
    | '/chat'
    | '/document-groups'
    | '/jobs'
    | '/kunden'
    | '/lieferanten'
    | '/login'
    | '/monitoring'
    | '/relationships'
    | '/search'
    | '/upload'
    | '/validation-queue'
    | '/admin/banking'
    | '/admin/datev'
    | '/admin/ocr-backends'
    | '/admin/ocr-review'
    | '/admin/ocr-training'
    | '/admin/settings'
    | '/admin/tunes'
    | '/admin/users'
    | '/business-entities/$id'
    | '/document-groups/$id'
    | '/documents/$documentId'
    | '/kunden/$customerId'
    | '/lieferanten/$supplierId'
    | '/validation-queue/$id'
    | '/admin/'
    | '/kunden/'
    | '/lieferanten/'
    | '/admin/banking/accounts'
    | '/admin/banking/import'
    | '/admin/banking/payments'
    | '/admin/banking/reconciliation'
    | '/admin/banking/skonto'
    | '/admin/banking/transactions'
    | '/admin/datev/config'
    | '/admin/datev/export'
    | '/admin/datev/history'
    | '/admin/datev/vendors'
    | '/admin/ocr-backends/$backend'
    | '/documents/$documentId/relationships'
    | '/kunden/$customerId/$folderId'
    | '/lieferanten/$supplierId/$folderId'
    | '/admin/banking/'
    | '/admin/datev/'
    | '/kunden/$customerId/'
    | '/lieferanten/$supplierId/'
    | '/admin/ocr-training/batch/$id'
    | '/kunden/$customerId/$folderId/$category'
    | '/lieferanten/$supplierId/$folderId/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/business-entities'
    | '/chat'
    | '/document-groups'
    | '/jobs'
    | '/login'
    | '/monitoring'
    | '/relationships'
    | '/search'
    | '/upload'
    | '/validation-queue'
    | '/admin/ocr-backends'
    | '/admin/ocr-review'
    | '/admin/ocr-training'
    | '/admin/settings'
    | '/admin/tunes'
    | '/admin/users'
    | '/business-entities/$id'
    | '/document-groups/$id'
    | '/documents/$documentId'
    | '/validation-queue/$id'
    | '/admin'
    | '/kunden'
    | '/lieferanten'
    | '/admin/banking/accounts'
    | '/admin/banking/import'
    | '/admin/banking/payments'
    | '/admin/banking/reconciliation'
    | '/admin/banking/skonto'
    | '/admin/banking/transactions'
    | '/admin/datev/config'
    | '/admin/datev/export'
    | '/admin/datev/history'
    | '/admin/datev/vendors'
    | '/admin/ocr-backends/$backend'
    | '/documents/$documentId/relationships'
    | '/kunden/$customerId/$folderId'
    | '/lieferanten/$supplierId/$folderId'
    | '/admin/banking'
    | '/admin/datev'
    | '/kunden/$customerId'
    | '/lieferanten/$supplierId'
    | '/admin/ocr-training/batch/$id'
    | '/kunden/$customerId/$folderId/$category'
    | '/lieferanten/$supplierId/$folderId/$category'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/automation'
    | '/business-entities'
    | '/chat'
    | '/document-groups'
    | '/jobs'
    | '/kunden'
    | '/lieferanten'
    | '/login'
    | '/monitoring'
    | '/relationships'
    | '/search'
    | '/upload'
    | '/validation-queue'
    | '/admin/banking'
    | '/admin/datev'
    | '/admin/ocr-backends'
    | '/admin/ocr-review'
    | '/admin/ocr-training'
    | '/admin/settings'
    | '/admin/tunes'
    | '/admin/users'
    | '/business-entities/$id'
    | '/document-groups/$id'
    | '/documents/$documentId'
    | '/kunden/$customerId'
    | '/lieferanten/$supplierId'
    | '/validation-queue/$id'
    | '/admin/'
    | '/kunden/'
    | '/lieferanten/'
    | '/admin/banking/accounts'
    | '/admin/banking/import'
    | '/admin/banking/payments'
    | '/admin/banking/reconciliation'
    | '/admin/banking/skonto'
    | '/admin/banking/transactions'
    | '/admin/datev/config'
    | '/admin/datev/export'
    | '/admin/datev/history'
    | '/admin/datev/vendors'
    | '/admin/ocr-backends/$backend'
    | '/documents/$documentId/relationships'
    | '/kunden/$customerId/$folderId'
    | '/lieferanten/$supplierId/$folderId'
    | '/admin/banking/'
    | '/admin/datev/'
    | '/kunden/$customerId/'
    | '/lieferanten/$supplierId/'
    | '/admin/ocr-training/batch/$id'
    | '/kunden/$customerId/$folderId/$category'
    | '/lieferanten/$supplierId/$folderId/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AutomationRoute: typeof AutomationRoute
  BusinessEntitiesRoute: typeof BusinessEntitiesRouteWithChildren
  ChatRoute: typeof ChatRoute
  DocumentGroupsRoute: typeof DocumentGroupsRouteWithChildren
  JobsRoute: typeof JobsRoute
  KundenRoute: typeof KundenRouteWithChildren
  LieferantenRoute: typeof LieferantenRouteWithChildren
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  RelationshipsRoute: typeof RelationshipsRoute
  SearchRoute: typeof SearchRoute
  UploadRoute: typeof UploadRoute
  ValidationQueueRoute: typeof ValidationQueueRouteWithChildren
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-queue': {
      id: '/validation-queue'
      path: '/validation-queue'
      fullPath: '/validation-queue'
      preLoaderRoute: typeof ValidationQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieferanten': {
      id: '/lieferanten'
      path: '/lieferanten'
      fullPath: '/lieferanten'
      preLoaderRoute: typeof LieferantenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden': {
      id: '/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof KundenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-groups': {
      id: '/document-groups'
      path: '/document-groups'
      fullPath: '/document-groups'
      preLoaderRoute: typeof DocumentGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-entities': {
      id: '/business-entities'
      path: '/business-entities'
      fullPath: '/business-entities'
      preLoaderRoute: typeof BusinessEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieferanten/': {
      id: '/lieferanten/'
      path: '/'
      fullPath: '/lieferanten/'
      preLoaderRoute: typeof LieferantenIndexRouteImport
      parentRoute: typeof LieferantenRoute
    }
    '/kunden/': {
      id: '/kunden/'
      path: '/'
      fullPath: '/kunden/'
      preLoaderRoute: typeof KundenIndexRouteImport
      parentRoute: typeof KundenRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/validation-queue/$id': {
      id: '/validation-queue/$id'
      path: '/$id'
      fullPath: '/validation-queue/$id'
      preLoaderRoute: typeof ValidationQueueIdRouteImport
      parentRoute: typeof ValidationQueueRoute
    }
    '/lieferanten/$supplierId': {
      id: '/lieferanten/$supplierId'
      path: '/$supplierId'
      fullPath: '/lieferanten/$supplierId'
      preLoaderRoute: typeof LieferantenSupplierIdRouteImport
      parentRoute: typeof LieferantenRoute
    }
    '/kunden/$customerId': {
      id: '/kunden/$customerId'
      path: '/$customerId'
      fullPath: '/kunden/$customerId'
      preLoaderRoute: typeof KundenCustomerIdRouteImport
      parentRoute: typeof KundenRoute
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-groups/$id': {
      id: '/document-groups/$id'
      path: '/$id'
      fullPath: '/document-groups/$id'
      preLoaderRoute: typeof DocumentGroupsIdRouteImport
      parentRoute: typeof DocumentGroupsRoute
    }
    '/business-entities/$id': {
      id: '/business-entities/$id'
      path: '/$id'
      fullPath: '/business-entities/$id'
      preLoaderRoute: typeof BusinessEntitiesIdRouteImport
      parentRoute: typeof BusinessEntitiesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tunes': {
      id: '/admin/tunes'
      path: '/tunes'
      fullPath: '/admin/tunes'
      preLoaderRoute: typeof AdminTunesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ocr-training': {
      id: '/admin/ocr-training'
      path: '/ocr-training'
      fullPath: '/admin/ocr-training'
      preLoaderRoute: typeof AdminOcrTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ocr-review': {
      id: '/admin/ocr-review'
      path: '/ocr-review'
      fullPath: '/admin/ocr-review'
      preLoaderRoute: typeof AdminOcrReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ocr-backends': {
      id: '/admin/ocr-backends'
      path: '/ocr-backends'
      fullPath: '/admin/ocr-backends'
      preLoaderRoute: typeof AdminOcrBackendsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/datev': {
      id: '/admin/datev'
      path: '/datev'
      fullPath: '/admin/datev'
      preLoaderRoute: typeof AdminDatevRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banking': {
      id: '/admin/banking'
      path: '/banking'
      fullPath: '/admin/banking'
      preLoaderRoute: typeof AdminBankingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lieferanten/$supplierId/': {
      id: '/lieferanten/$supplierId/'
      path: '/'
      fullPath: '/lieferanten/$supplierId/'
      preLoaderRoute: typeof LieferantenSupplierIdIndexRouteImport
      parentRoute: typeof LieferantenSupplierIdRoute
    }
    '/kunden/$customerId/': {
      id: '/kunden/$customerId/'
      path: '/'
      fullPath: '/kunden/$customerId/'
      preLoaderRoute: typeof KundenCustomerIdIndexRouteImport
      parentRoute: typeof KundenCustomerIdRoute
    }
    '/admin/datev/': {
      id: '/admin/datev/'
      path: '/'
      fullPath: '/admin/datev/'
      preLoaderRoute: typeof AdminDatevIndexRouteImport
      parentRoute: typeof AdminDatevRoute
    }
    '/admin/banking/': {
      id: '/admin/banking/'
      path: '/'
      fullPath: '/admin/banking/'
      preLoaderRoute: typeof AdminBankingIndexRouteImport
      parentRoute: typeof AdminBankingRoute
    }
    '/lieferanten/$supplierId/$folderId': {
      id: '/lieferanten/$supplierId/$folderId'
      path: '/$folderId'
      fullPath: '/lieferanten/$supplierId/$folderId'
      preLoaderRoute: typeof LieferantenSupplierIdFolderIdRouteImport
      parentRoute: typeof LieferantenSupplierIdRoute
    }
    '/kunden/$customerId/$folderId': {
      id: '/kunden/$customerId/$folderId'
      path: '/$folderId'
      fullPath: '/kunden/$customerId/$folderId'
      preLoaderRoute: typeof KundenCustomerIdFolderIdRouteImport
      parentRoute: typeof KundenCustomerIdRoute
    }
    '/documents/$documentId/relationships': {
      id: '/documents/$documentId/relationships'
      path: '/relationships'
      fullPath: '/documents/$documentId/relationships'
      preLoaderRoute: typeof DocumentsDocumentIdRelationshipsRouteImport
      parentRoute: typeof DocumentsDocumentIdRoute
    }
    '/admin/ocr-backends/$backend': {
      id: '/admin/ocr-backends/$backend'
      path: '/$backend'
      fullPath: '/admin/ocr-backends/$backend'
      preLoaderRoute: typeof AdminOcrBackendsBackendRouteImport
      parentRoute: typeof AdminOcrBackendsRoute
    }
    '/admin/datev/vendors': {
      id: '/admin/datev/vendors'
      path: '/vendors'
      fullPath: '/admin/datev/vendors'
      preLoaderRoute: typeof AdminDatevVendorsRouteImport
      parentRoute: typeof AdminDatevRoute
    }
    '/admin/datev/history': {
      id: '/admin/datev/history'
      path: '/history'
      fullPath: '/admin/datev/history'
      preLoaderRoute: typeof AdminDatevHistoryRouteImport
      parentRoute: typeof AdminDatevRoute
    }
    '/admin/datev/export': {
      id: '/admin/datev/export'
      path: '/export'
      fullPath: '/admin/datev/export'
      preLoaderRoute: typeof AdminDatevExportRouteImport
      parentRoute: typeof AdminDatevRoute
    }
    '/admin/datev/config': {
      id: '/admin/datev/config'
      path: '/config'
      fullPath: '/admin/datev/config'
      preLoaderRoute: typeof AdminDatevConfigRouteImport
      parentRoute: typeof AdminDatevRoute
    }
    '/admin/banking/transactions': {
      id: '/admin/banking/transactions'
      path: '/transactions'
      fullPath: '/admin/banking/transactions'
      preLoaderRoute: typeof AdminBankingTransactionsRouteImport
      parentRoute: typeof AdminBankingRoute
    }
    '/admin/banking/skonto': {
      id: '/admin/banking/skonto'
      path: '/skonto'
      fullPath: '/admin/banking/skonto'
      preLoaderRoute: typeof AdminBankingSkontoRouteImport
      parentRoute: typeof AdminBankingRoute
    }
    '/admin/banking/reconciliation': {
      id: '/admin/banking/reconciliation'
      path: '/reconciliation'
      fullPath: '/admin/banking/reconciliation'
      preLoaderRoute: typeof AdminBankingReconciliationRouteImport
      parentRoute: typeof AdminBankingRoute
    }
    '/admin/banking/payments': {
      id: '/admin/banking/payments'
      path: '/payments'
      fullPath: '/admin/banking/payments'
      preLoaderRoute: typeof AdminBankingPaymentsRouteImport
      parentRoute: typeof AdminBankingRoute
    }
    '/admin/banking/import': {
      id: '/admin/banking/import'
      path: '/import'
      fullPath: '/admin/banking/import'
      preLoaderRoute: typeof AdminBankingImportRouteImport
      parentRoute: typeof AdminBankingRoute
    }
    '/admin/banking/accounts': {
      id: '/admin/banking/accounts'
      path: '/accounts'
      fullPath: '/admin/banking/accounts'
      preLoaderRoute: typeof AdminBankingAccountsRouteImport
      parentRoute: typeof AdminBankingRoute
    }
    '/lieferanten/$supplierId/$folderId/$category': {
      id: '/lieferanten/$supplierId/$folderId/$category'
      path: '/$category'
      fullPath: '/lieferanten/$supplierId/$folderId/$category'
      preLoaderRoute: typeof LieferantenSupplierIdFolderIdCategoryRouteImport
      parentRoute: typeof LieferantenSupplierIdFolderIdRoute
    }
    '/kunden/$customerId/$folderId/$category': {
      id: '/kunden/$customerId/$folderId/$category'
      path: '/$category'
      fullPath: '/kunden/$customerId/$folderId/$category'
      preLoaderRoute: typeof KundenCustomerIdFolderIdCategoryRouteImport
      parentRoute: typeof KundenCustomerIdFolderIdRoute
    }
    '/admin/ocr-training/batch/$id': {
      id: '/admin/ocr-training/batch/$id'
      path: '/batch/$id'
      fullPath: '/admin/ocr-training/batch/$id'
      preLoaderRoute: typeof AdminOcrTrainingBatchIdRouteImport
      parentRoute: typeof AdminOcrTrainingRoute
    }
  }
}

interface AdminBankingRouteChildren {
  AdminBankingAccountsRoute: typeof AdminBankingAccountsRoute
  AdminBankingImportRoute: typeof AdminBankingImportRoute
  AdminBankingPaymentsRoute: typeof AdminBankingPaymentsRoute
  AdminBankingReconciliationRoute: typeof AdminBankingReconciliationRoute
  AdminBankingSkontoRoute: typeof AdminBankingSkontoRoute
  AdminBankingTransactionsRoute: typeof AdminBankingTransactionsRoute
  AdminBankingIndexRoute: typeof AdminBankingIndexRoute
}

const AdminBankingRouteChildren: AdminBankingRouteChildren = {
  AdminBankingAccountsRoute: AdminBankingAccountsRoute,
  AdminBankingImportRoute: AdminBankingImportRoute,
  AdminBankingPaymentsRoute: AdminBankingPaymentsRoute,
  AdminBankingReconciliationRoute: AdminBankingReconciliationRoute,
  AdminBankingSkontoRoute: AdminBankingSkontoRoute,
  AdminBankingTransactionsRoute: AdminBankingTransactionsRoute,
  AdminBankingIndexRoute: AdminBankingIndexRoute,
}

const AdminBankingRouteWithChildren = AdminBankingRoute._addFileChildren(
  AdminBankingRouteChildren,
)

interface AdminDatevRouteChildren {
  AdminDatevConfigRoute: typeof AdminDatevConfigRoute
  AdminDatevExportRoute: typeof AdminDatevExportRoute
  AdminDatevHistoryRoute: typeof AdminDatevHistoryRoute
  AdminDatevVendorsRoute: typeof AdminDatevVendorsRoute
  AdminDatevIndexRoute: typeof AdminDatevIndexRoute
}

const AdminDatevRouteChildren: AdminDatevRouteChildren = {
  AdminDatevConfigRoute: AdminDatevConfigRoute,
  AdminDatevExportRoute: AdminDatevExportRoute,
  AdminDatevHistoryRoute: AdminDatevHistoryRoute,
  AdminDatevVendorsRoute: AdminDatevVendorsRoute,
  AdminDatevIndexRoute: AdminDatevIndexRoute,
}

const AdminDatevRouteWithChildren = AdminDatevRoute._addFileChildren(
  AdminDatevRouteChildren,
)

interface AdminOcrBackendsRouteChildren {
  AdminOcrBackendsBackendRoute: typeof AdminOcrBackendsBackendRoute
}

const AdminOcrBackendsRouteChildren: AdminOcrBackendsRouteChildren = {
  AdminOcrBackendsBackendRoute: AdminOcrBackendsBackendRoute,
}

const AdminOcrBackendsRouteWithChildren =
  AdminOcrBackendsRoute._addFileChildren(AdminOcrBackendsRouteChildren)

interface AdminOcrTrainingRouteChildren {
  AdminOcrTrainingBatchIdRoute: typeof AdminOcrTrainingBatchIdRoute
}

const AdminOcrTrainingRouteChildren: AdminOcrTrainingRouteChildren = {
  AdminOcrTrainingBatchIdRoute: AdminOcrTrainingBatchIdRoute,
}

const AdminOcrTrainingRouteWithChildren =
  AdminOcrTrainingRoute._addFileChildren(AdminOcrTrainingRouteChildren)

interface AdminRouteChildren {
  AdminBankingRoute: typeof AdminBankingRouteWithChildren
  AdminDatevRoute: typeof AdminDatevRouteWithChildren
  AdminOcrBackendsRoute: typeof AdminOcrBackendsRouteWithChildren
  AdminOcrReviewRoute: typeof AdminOcrReviewRoute
  AdminOcrTrainingRoute: typeof AdminOcrTrainingRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTunesRoute: typeof AdminTunesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBankingRoute: AdminBankingRouteWithChildren,
  AdminDatevRoute: AdminDatevRouteWithChildren,
  AdminOcrBackendsRoute: AdminOcrBackendsRouteWithChildren,
  AdminOcrReviewRoute: AdminOcrReviewRoute,
  AdminOcrTrainingRoute: AdminOcrTrainingRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTunesRoute: AdminTunesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BusinessEntitiesRouteChildren {
  BusinessEntitiesIdRoute: typeof BusinessEntitiesIdRoute
}

const BusinessEntitiesRouteChildren: BusinessEntitiesRouteChildren = {
  BusinessEntitiesIdRoute: BusinessEntitiesIdRoute,
}

const BusinessEntitiesRouteWithChildren =
  BusinessEntitiesRoute._addFileChildren(BusinessEntitiesRouteChildren)

interface DocumentGroupsRouteChildren {
  DocumentGroupsIdRoute: typeof DocumentGroupsIdRoute
}

const DocumentGroupsRouteChildren: DocumentGroupsRouteChildren = {
  DocumentGroupsIdRoute: DocumentGroupsIdRoute,
}

const DocumentGroupsRouteWithChildren = DocumentGroupsRoute._addFileChildren(
  DocumentGroupsRouteChildren,
)

interface KundenCustomerIdFolderIdRouteChildren {
  KundenCustomerIdFolderIdCategoryRoute: typeof KundenCustomerIdFolderIdCategoryRoute
}

const KundenCustomerIdFolderIdRouteChildren: KundenCustomerIdFolderIdRouteChildren =
  {
    KundenCustomerIdFolderIdCategoryRoute:
      KundenCustomerIdFolderIdCategoryRoute,
  }

const KundenCustomerIdFolderIdRouteWithChildren =
  KundenCustomerIdFolderIdRoute._addFileChildren(
    KundenCustomerIdFolderIdRouteChildren,
  )

interface KundenCustomerIdRouteChildren {
  KundenCustomerIdFolderIdRoute: typeof KundenCustomerIdFolderIdRouteWithChildren
  KundenCustomerIdIndexRoute: typeof KundenCustomerIdIndexRoute
}

const KundenCustomerIdRouteChildren: KundenCustomerIdRouteChildren = {
  KundenCustomerIdFolderIdRoute: KundenCustomerIdFolderIdRouteWithChildren,
  KundenCustomerIdIndexRoute: KundenCustomerIdIndexRoute,
}

const KundenCustomerIdRouteWithChildren =
  KundenCustomerIdRoute._addFileChildren(KundenCustomerIdRouteChildren)

interface KundenRouteChildren {
  KundenCustomerIdRoute: typeof KundenCustomerIdRouteWithChildren
  KundenIndexRoute: typeof KundenIndexRoute
}

const KundenRouteChildren: KundenRouteChildren = {
  KundenCustomerIdRoute: KundenCustomerIdRouteWithChildren,
  KundenIndexRoute: KundenIndexRoute,
}

const KundenRouteWithChildren =
  KundenRoute._addFileChildren(KundenRouteChildren)

interface LieferantenSupplierIdFolderIdRouteChildren {
  LieferantenSupplierIdFolderIdCategoryRoute: typeof LieferantenSupplierIdFolderIdCategoryRoute
}

const LieferantenSupplierIdFolderIdRouteChildren: LieferantenSupplierIdFolderIdRouteChildren =
  {
    LieferantenSupplierIdFolderIdCategoryRoute:
      LieferantenSupplierIdFolderIdCategoryRoute,
  }

const LieferantenSupplierIdFolderIdRouteWithChildren =
  LieferantenSupplierIdFolderIdRoute._addFileChildren(
    LieferantenSupplierIdFolderIdRouteChildren,
  )

interface LieferantenSupplierIdRouteChildren {
  LieferantenSupplierIdFolderIdRoute: typeof LieferantenSupplierIdFolderIdRouteWithChildren
  LieferantenSupplierIdIndexRoute: typeof LieferantenSupplierIdIndexRoute
}

const LieferantenSupplierIdRouteChildren: LieferantenSupplierIdRouteChildren = {
  LieferantenSupplierIdFolderIdRoute:
    LieferantenSupplierIdFolderIdRouteWithChildren,
  LieferantenSupplierIdIndexRoute: LieferantenSupplierIdIndexRoute,
}

const LieferantenSupplierIdRouteWithChildren =
  LieferantenSupplierIdRoute._addFileChildren(
    LieferantenSupplierIdRouteChildren,
  )

interface LieferantenRouteChildren {
  LieferantenSupplierIdRoute: typeof LieferantenSupplierIdRouteWithChildren
  LieferantenIndexRoute: typeof LieferantenIndexRoute
}

const LieferantenRouteChildren: LieferantenRouteChildren = {
  LieferantenSupplierIdRoute: LieferantenSupplierIdRouteWithChildren,
  LieferantenIndexRoute: LieferantenIndexRoute,
}

const LieferantenRouteWithChildren = LieferantenRoute._addFileChildren(
  LieferantenRouteChildren,
)

interface ValidationQueueRouteChildren {
  ValidationQueueIdRoute: typeof ValidationQueueIdRoute
}

const ValidationQueueRouteChildren: ValidationQueueRouteChildren = {
  ValidationQueueIdRoute: ValidationQueueIdRoute,
}

const ValidationQueueRouteWithChildren = ValidationQueueRoute._addFileChildren(
  ValidationQueueRouteChildren,
)

interface DocumentsDocumentIdRouteChildren {
  DocumentsDocumentIdRelationshipsRoute: typeof DocumentsDocumentIdRelationshipsRoute
}

const DocumentsDocumentIdRouteChildren: DocumentsDocumentIdRouteChildren = {
  DocumentsDocumentIdRelationshipsRoute: DocumentsDocumentIdRelationshipsRoute,
}

const DocumentsDocumentIdRouteWithChildren =
  DocumentsDocumentIdRoute._addFileChildren(DocumentsDocumentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AutomationRoute: AutomationRoute,
  BusinessEntitiesRoute: BusinessEntitiesRouteWithChildren,
  ChatRoute: ChatRoute,
  DocumentGroupsRoute: DocumentGroupsRouteWithChildren,
  JobsRoute: JobsRoute,
  KundenRoute: KundenRouteWithChildren,
  LieferantenRoute: LieferantenRouteWithChildren,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  RelationshipsRoute: RelationshipsRoute,
  SearchRoute: SearchRoute,
  UploadRoute: UploadRoute,
  ValidationQueueRoute: ValidationQueueRouteWithChildren,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
