/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as ValidationQueueRouteImport } from './app/routes/validation-queue'
import { Route as UploadRouteImport } from './app/routes/upload'
import { Route as SearchRouteImport } from './app/routes/search'
import { Route as RelationshipsRouteImport } from './app/routes/relationships'
import { Route as MonitoringRouteImport } from './app/routes/monitoring'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as JobsRouteImport } from './app/routes/jobs'
import { Route as DocumentGroupsRouteImport } from './app/routes/document-groups'
import { Route as BusinessEntitiesRouteImport } from './app/routes/business-entities'
import { Route as AutomationRouteImport } from './app/routes/automation'
import { Route as AdminRouteImport } from './app/routes/admin'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ValidationQueueIdRouteImport } from './app/routes/validation-queue.$id'
import { Route as DocumentsDocumentIdRouteImport } from './app/routes/documents.$documentId'
import { Route as DocumentGroupsIdRouteImport } from './app/routes/document-groups.$id'
import { Route as BusinessEntitiesIdRouteImport } from './app/routes/business-entities.$id'
import { Route as AdminUsersRouteImport } from './app/routes/admin.users'
import { Route as AdminTunesRouteImport } from './app/routes/admin.tunes'
import { Route as AdminOcrTrainingRouteImport } from './app/routes/admin.ocr-training'
import { Route as AdminOcrBackendsRouteImport } from './app/routes/admin.ocr-backends'
import { Route as DocumentsDocumentIdRelationshipsRouteImport } from './app/routes/documents.$documentId.relationships'
import { Route as AdminOcrBackendsBackendRouteImport } from './app/routes/admin.ocr-backends.$backend'
import { Route as AdminOcrTrainingBatchIdRouteImport } from './app/routes/admin.ocr-training.batch.$id'

const ValidationQueueRoute = ValidationQueueRouteImport.update({
  id: '/validation-queue',
  path: '/validation-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentGroupsRoute = DocumentGroupsRouteImport.update({
  id: '/document-groups',
  path: '/document-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessEntitiesRoute = BusinessEntitiesRouteImport.update({
  id: '/business-entities',
  path: '/business-entities',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationQueueIdRoute = ValidationQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ValidationQueueRoute,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentGroupsIdRoute = DocumentGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentGroupsRoute,
} as any)
const BusinessEntitiesIdRoute = BusinessEntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusinessEntitiesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTunesRoute = AdminTunesRouteImport.update({
  id: '/tunes',
  path: '/tunes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOcrTrainingRoute = AdminOcrTrainingRouteImport.update({
  id: '/ocr-training',
  path: '/ocr-training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOcrBackendsRoute = AdminOcrBackendsRouteImport.update({
  id: '/ocr-backends',
  path: '/ocr-backends',
  getParentRoute: () => AdminRoute,
} as any)
const DocumentsDocumentIdRelationshipsRoute =
  DocumentsDocumentIdRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => DocumentsDocumentIdRoute,
  } as any)
const AdminOcrBackendsBackendRoute = AdminOcrBackendsBackendRouteImport.update({
  id: '/$backend',
  path: '/$backend',
  getParentRoute: () => AdminOcrBackendsRoute,
} as any)
const AdminOcrTrainingBatchIdRoute = AdminOcrTrainingBatchIdRouteImport.update({
  id: '/batch/$id',
  path: '/batch/$id',
  getParentRoute: () => AdminOcrTrainingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/automation': typeof AutomationRoute
  '/business-entities': typeof BusinessEntitiesRouteWithChildren
  '/document-groups': typeof DocumentGroupsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relationships': typeof RelationshipsRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/validation-queue': typeof ValidationQueueRouteWithChildren
  '/admin/ocr-backends': typeof AdminOcrBackendsRouteWithChildren
  '/admin/ocr-training': typeof AdminOcrTrainingRouteWithChildren
  '/admin/tunes': typeof AdminTunesRoute
  '/admin/users': typeof AdminUsersRoute
  '/business-entities/$id': typeof BusinessEntitiesIdRoute
  '/document-groups/$id': typeof DocumentGroupsIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRouteWithChildren
  '/validation-queue/$id': typeof ValidationQueueIdRoute
  '/admin/ocr-backends/$backend': typeof AdminOcrBackendsBackendRoute
  '/documents/$documentId/relationships': typeof DocumentsDocumentIdRelationshipsRoute
  '/admin/ocr-training/batch/$id': typeof AdminOcrTrainingBatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/automation': typeof AutomationRoute
  '/business-entities': typeof BusinessEntitiesRouteWithChildren
  '/document-groups': typeof DocumentGroupsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relationships': typeof RelationshipsRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/validation-queue': typeof ValidationQueueRouteWithChildren
  '/admin/ocr-backends': typeof AdminOcrBackendsRouteWithChildren
  '/admin/ocr-training': typeof AdminOcrTrainingRouteWithChildren
  '/admin/tunes': typeof AdminTunesRoute
  '/admin/users': typeof AdminUsersRoute
  '/business-entities/$id': typeof BusinessEntitiesIdRoute
  '/document-groups/$id': typeof DocumentGroupsIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRouteWithChildren
  '/validation-queue/$id': typeof ValidationQueueIdRoute
  '/admin/ocr-backends/$backend': typeof AdminOcrBackendsBackendRoute
  '/documents/$documentId/relationships': typeof DocumentsDocumentIdRelationshipsRoute
  '/admin/ocr-training/batch/$id': typeof AdminOcrTrainingBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/automation': typeof AutomationRoute
  '/business-entities': typeof BusinessEntitiesRouteWithChildren
  '/document-groups': typeof DocumentGroupsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relationships': typeof RelationshipsRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/validation-queue': typeof ValidationQueueRouteWithChildren
  '/admin/ocr-backends': typeof AdminOcrBackendsRouteWithChildren
  '/admin/ocr-training': typeof AdminOcrTrainingRouteWithChildren
  '/admin/tunes': typeof AdminTunesRoute
  '/admin/users': typeof AdminUsersRoute
  '/business-entities/$id': typeof BusinessEntitiesIdRoute
  '/document-groups/$id': typeof DocumentGroupsIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRouteWithChildren
  '/validation-queue/$id': typeof ValidationQueueIdRoute
  '/admin/ocr-backends/$backend': typeof AdminOcrBackendsBackendRoute
  '/documents/$documentId/relationships': typeof DocumentsDocumentIdRelationshipsRoute
  '/admin/ocr-training/batch/$id': typeof AdminOcrTrainingBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/automation'
    | '/business-entities'
    | '/document-groups'
    | '/jobs'
    | '/login'
    | '/monitoring'
    | '/relationships'
    | '/search'
    | '/upload'
    | '/validation-queue'
    | '/admin/ocr-backends'
    | '/admin/ocr-training'
    | '/admin/tunes'
    | '/admin/users'
    | '/business-entities/$id'
    | '/document-groups/$id'
    | '/documents/$documentId'
    | '/validation-queue/$id'
    | '/admin/ocr-backends/$backend'
    | '/documents/$documentId/relationships'
    | '/admin/ocr-training/batch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/automation'
    | '/business-entities'
    | '/document-groups'
    | '/jobs'
    | '/login'
    | '/monitoring'
    | '/relationships'
    | '/search'
    | '/upload'
    | '/validation-queue'
    | '/admin/ocr-backends'
    | '/admin/ocr-training'
    | '/admin/tunes'
    | '/admin/users'
    | '/business-entities/$id'
    | '/document-groups/$id'
    | '/documents/$documentId'
    | '/validation-queue/$id'
    | '/admin/ocr-backends/$backend'
    | '/documents/$documentId/relationships'
    | '/admin/ocr-training/batch/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/automation'
    | '/business-entities'
    | '/document-groups'
    | '/jobs'
    | '/login'
    | '/monitoring'
    | '/relationships'
    | '/search'
    | '/upload'
    | '/validation-queue'
    | '/admin/ocr-backends'
    | '/admin/ocr-training'
    | '/admin/tunes'
    | '/admin/users'
    | '/business-entities/$id'
    | '/document-groups/$id'
    | '/documents/$documentId'
    | '/validation-queue/$id'
    | '/admin/ocr-backends/$backend'
    | '/documents/$documentId/relationships'
    | '/admin/ocr-training/batch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AutomationRoute: typeof AutomationRoute
  BusinessEntitiesRoute: typeof BusinessEntitiesRouteWithChildren
  DocumentGroupsRoute: typeof DocumentGroupsRouteWithChildren
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  RelationshipsRoute: typeof RelationshipsRoute
  SearchRoute: typeof SearchRoute
  UploadRoute: typeof UploadRoute
  ValidationQueueRoute: typeof ValidationQueueRouteWithChildren
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-queue': {
      id: '/validation-queue'
      path: '/validation-queue'
      fullPath: '/validation-queue'
      preLoaderRoute: typeof ValidationQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-groups': {
      id: '/document-groups'
      path: '/document-groups'
      fullPath: '/document-groups'
      preLoaderRoute: typeof DocumentGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-entities': {
      id: '/business-entities'
      path: '/business-entities'
      fullPath: '/business-entities'
      preLoaderRoute: typeof BusinessEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation-queue/$id': {
      id: '/validation-queue/$id'
      path: '/$id'
      fullPath: '/validation-queue/$id'
      preLoaderRoute: typeof ValidationQueueIdRouteImport
      parentRoute: typeof ValidationQueueRoute
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-groups/$id': {
      id: '/document-groups/$id'
      path: '/$id'
      fullPath: '/document-groups/$id'
      preLoaderRoute: typeof DocumentGroupsIdRouteImport
      parentRoute: typeof DocumentGroupsRoute
    }
    '/business-entities/$id': {
      id: '/business-entities/$id'
      path: '/$id'
      fullPath: '/business-entities/$id'
      preLoaderRoute: typeof BusinessEntitiesIdRouteImport
      parentRoute: typeof BusinessEntitiesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tunes': {
      id: '/admin/tunes'
      path: '/tunes'
      fullPath: '/admin/tunes'
      preLoaderRoute: typeof AdminTunesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ocr-training': {
      id: '/admin/ocr-training'
      path: '/ocr-training'
      fullPath: '/admin/ocr-training'
      preLoaderRoute: typeof AdminOcrTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ocr-backends': {
      id: '/admin/ocr-backends'
      path: '/ocr-backends'
      fullPath: '/admin/ocr-backends'
      preLoaderRoute: typeof AdminOcrBackendsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/documents/$documentId/relationships': {
      id: '/documents/$documentId/relationships'
      path: '/relationships'
      fullPath: '/documents/$documentId/relationships'
      preLoaderRoute: typeof DocumentsDocumentIdRelationshipsRouteImport
      parentRoute: typeof DocumentsDocumentIdRoute
    }
    '/admin/ocr-backends/$backend': {
      id: '/admin/ocr-backends/$backend'
      path: '/$backend'
      fullPath: '/admin/ocr-backends/$backend'
      preLoaderRoute: typeof AdminOcrBackendsBackendRouteImport
      parentRoute: typeof AdminOcrBackendsRoute
    }
    '/admin/ocr-training/batch/$id': {
      id: '/admin/ocr-training/batch/$id'
      path: '/batch/$id'
      fullPath: '/admin/ocr-training/batch/$id'
      preLoaderRoute: typeof AdminOcrTrainingBatchIdRouteImport
      parentRoute: typeof AdminOcrTrainingRoute
    }
  }
}

interface AdminOcrBackendsRouteChildren {
  AdminOcrBackendsBackendRoute: typeof AdminOcrBackendsBackendRoute
}

const AdminOcrBackendsRouteChildren: AdminOcrBackendsRouteChildren = {
  AdminOcrBackendsBackendRoute: AdminOcrBackendsBackendRoute,
}

const AdminOcrBackendsRouteWithChildren =
  AdminOcrBackendsRoute._addFileChildren(AdminOcrBackendsRouteChildren)

interface AdminOcrTrainingRouteChildren {
  AdminOcrTrainingBatchIdRoute: typeof AdminOcrTrainingBatchIdRoute
}

const AdminOcrTrainingRouteChildren: AdminOcrTrainingRouteChildren = {
  AdminOcrTrainingBatchIdRoute: AdminOcrTrainingBatchIdRoute,
}

const AdminOcrTrainingRouteWithChildren =
  AdminOcrTrainingRoute._addFileChildren(AdminOcrTrainingRouteChildren)

interface AdminRouteChildren {
  AdminOcrBackendsRoute: typeof AdminOcrBackendsRouteWithChildren
  AdminOcrTrainingRoute: typeof AdminOcrTrainingRouteWithChildren
  AdminTunesRoute: typeof AdminTunesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOcrBackendsRoute: AdminOcrBackendsRouteWithChildren,
  AdminOcrTrainingRoute: AdminOcrTrainingRouteWithChildren,
  AdminTunesRoute: AdminTunesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BusinessEntitiesRouteChildren {
  BusinessEntitiesIdRoute: typeof BusinessEntitiesIdRoute
}

const BusinessEntitiesRouteChildren: BusinessEntitiesRouteChildren = {
  BusinessEntitiesIdRoute: BusinessEntitiesIdRoute,
}

const BusinessEntitiesRouteWithChildren =
  BusinessEntitiesRoute._addFileChildren(BusinessEntitiesRouteChildren)

interface DocumentGroupsRouteChildren {
  DocumentGroupsIdRoute: typeof DocumentGroupsIdRoute
}

const DocumentGroupsRouteChildren: DocumentGroupsRouteChildren = {
  DocumentGroupsIdRoute: DocumentGroupsIdRoute,
}

const DocumentGroupsRouteWithChildren = DocumentGroupsRoute._addFileChildren(
  DocumentGroupsRouteChildren,
)

interface ValidationQueueRouteChildren {
  ValidationQueueIdRoute: typeof ValidationQueueIdRoute
}

const ValidationQueueRouteChildren: ValidationQueueRouteChildren = {
  ValidationQueueIdRoute: ValidationQueueIdRoute,
}

const ValidationQueueRouteWithChildren = ValidationQueueRoute._addFileChildren(
  ValidationQueueRouteChildren,
)

interface DocumentsDocumentIdRouteChildren {
  DocumentsDocumentIdRelationshipsRoute: typeof DocumentsDocumentIdRelationshipsRoute
}

const DocumentsDocumentIdRouteChildren: DocumentsDocumentIdRouteChildren = {
  DocumentsDocumentIdRelationshipsRoute: DocumentsDocumentIdRelationshipsRoute,
}

const DocumentsDocumentIdRouteWithChildren =
  DocumentsDocumentIdRoute._addFileChildren(DocumentsDocumentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AutomationRoute: AutomationRoute,
  BusinessEntitiesRoute: BusinessEntitiesRouteWithChildren,
  DocumentGroupsRoute: DocumentGroupsRouteWithChildren,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  RelationshipsRoute: RelationshipsRoute,
  SearchRoute: SearchRoute,
  UploadRoute: UploadRoute,
  ValidationQueueRoute: ValidationQueueRouteWithChildren,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
