"""RAG Metrics Service.

Prometheus Metriken fuer den RAG Intelligence Layer:
- Search Requests & Latenz
- LLM Requests & Tokens
- Customer Card Lookups
- Chunking Stats
"""

import structlog
from typing import Optional
from datetime import datetime, timezone

try:
    from prometheus_client import Counter, Histogram, Gauge, Info
    PROMETHEUS_AVAILABLE = True
except ImportError:
    PROMETHEUS_AVAILABLE = False

logger = structlog.get_logger(__name__)


# =============================================================================
# Prometheus Metriken
# =============================================================================

if PROMETHEUS_AVAILABLE:
    # Search Metriken
    RAG_SEARCH_REQUESTS = Counter(
        "rag_search_requests_total",
        "Total RAG search requests",
        ["search_type", "status"]
    )

    RAG_SEARCH_LATENCY = Histogram(
        "rag_search_latency_seconds",
        "RAG search latency in seconds",
        ["search_type"],
        buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0]
    )

    RAG_SEARCH_RESULTS = Histogram(
        "rag_search_results_count",
        "Number of results returned by RAG search",
        ["search_type"],
        buckets=[0, 1, 5, 10, 20, 50, 100]
    )

    # LLM Metriken
    RAG_LLM_REQUESTS = Counter(
        "rag_llm_requests_total",
        "Total LLM requests",
        ["model", "context_type", "status"]
    )

    RAG_LLM_LATENCY = Histogram(
        "rag_llm_latency_seconds",
        "LLM generation latency in seconds",
        ["model", "context_type"],
        buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0]
    )

    RAG_LLM_TOKENS_INPUT = Counter(
        "rag_llm_tokens_input_total",
        "Total input tokens processed by LLM",
        ["model"]
    )

    RAG_LLM_TOKENS_OUTPUT = Counter(
        "rag_llm_tokens_output_total",
        "Total output tokens generated by LLM",
        ["model"]
    )

    # Customer Card Metriken
    RAG_CUSTOMER_CARD_LOOKUPS = Counter(
        "rag_customer_card_lookups_total",
        "Total customer card lookups",
        ["source", "status"]  # source: cache, database, generated
    )

    RAG_CUSTOMER_CARD_GENERATION_LATENCY = Histogram(
        "rag_customer_card_generation_seconds",
        "Customer card generation latency in seconds",
        buckets=[1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0]
    )

    RAG_CUSTOMER_CARD_SYNC_DURATION = Histogram(
        "rag_customer_card_sync_duration_seconds",
        "Duration of customer card sync job in seconds",
        buckets=[60, 300, 600, 1800, 3600]
    )

    # Chunking Metriken
    RAG_CHUNKING_REQUESTS = Counter(
        "rag_chunking_requests_total",
        "Total document chunking requests",
        ["strategy", "status"]
    )

    RAG_CHUNKING_LATENCY = Histogram(
        "rag_chunking_latency_seconds",
        "Document chunking latency in seconds",
        ["strategy"],
        buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0]
    )

    RAG_CHUNKS_CREATED = Counter(
        "rag_chunks_created_total",
        "Total chunks created",
        ["strategy", "section_type"]
    )

    RAG_CHUNK_TOKENS = Histogram(
        "rag_chunk_tokens",
        "Token count per chunk",
        ["strategy"],
        buckets=[50, 100, 200, 300, 500, 750, 1000, 1500, 2000]
    )

    # Chat Metriken
    RAG_CHAT_MESSAGES = Counter(
        "rag_chat_messages_total",
        "Total chat messages",
        ["role", "context_type"]
    )

    RAG_CHAT_SESSIONS = Gauge(
        "rag_chat_sessions_active",
        "Number of active chat sessions"
    )

    # Batch Job Metriken
    RAG_BATCH_JOBS = Counter(
        "rag_batch_jobs_total",
        "Total batch jobs",
        ["job_type", "status"]
    )

    RAG_BATCH_JOB_DURATION = Histogram(
        "rag_batch_job_duration_seconds",
        "Batch job duration in seconds",
        ["job_type"],
        buckets=[60, 300, 600, 1800, 3600, 7200]
    )

    # Reranker Metriken
    RAG_RERANK_REQUESTS = Counter(
        "rag_rerank_requests_total",
        "Total reranking requests",
        ["backend", "status"]  # backend: gpu, cpu
    )

    RAG_RERANK_LATENCY = Histogram(
        "rag_rerank_latency_seconds",
        "Reranking latency in seconds",
        ["backend"],
        buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0]
    )

    RAG_RERANK_DOCUMENTS = Histogram(
        "rag_rerank_documents_count",
        "Number of documents reranked per request",
        ["backend"],
        buckets=[1, 5, 10, 20, 50, 100]
    )

    RAG_RERANK_FALLBACKS = Counter(
        "rag_rerank_fallbacks_total",
        "Total GPU to CPU fallbacks",
        ["reason"]  # reason: oom, error, vram_low
    )

    RAG_RERANK_MODEL_LOADED = Gauge(
        "rag_rerank_model_loaded",
        "Whether reranker model is loaded",
        ["backend", "model"]
    )

    # System Info
    RAG_INFO = Info(
        "rag_system",
        "RAG system information"
    )


# =============================================================================
# Metrics Service
# =============================================================================

class RAGMetricsService:
    """Service fuer RAG Metriken."""

    def __init__(self):
        self._enabled = PROMETHEUS_AVAILABLE
        if not self._enabled:
            logger.warning("prometheus_client_not_available")

    @property
    def enabled(self) -> bool:
        """Prueft ob Metriken aktiviert sind."""
        return self._enabled

    # -------------------------------------------------------------------------
    # Search Metriken
    # -------------------------------------------------------------------------

    def record_search_request(
        self,
        search_type: str,
        status: str = "success",
        latency_seconds: Optional[float] = None,
        result_count: Optional[int] = None
    ):
        """Zeichnet Search Request auf."""
        if not self._enabled:
            return

        RAG_SEARCH_REQUESTS.labels(
            search_type=search_type,
            status=status
        ).inc()

        if latency_seconds is not None:
            RAG_SEARCH_LATENCY.labels(
                search_type=search_type
            ).observe(latency_seconds)

        if result_count is not None:
            RAG_SEARCH_RESULTS.labels(
                search_type=search_type
            ).observe(result_count)

    # -------------------------------------------------------------------------
    # LLM Metriken
    # -------------------------------------------------------------------------

    def record_llm_request(
        self,
        model: str,
        context_type: str,
        status: str = "success",
        latency_seconds: Optional[float] = None,
        tokens_input: Optional[int] = None,
        tokens_output: Optional[int] = None
    ):
        """Zeichnet LLM Request auf."""
        if not self._enabled:
            return

        RAG_LLM_REQUESTS.labels(
            model=model,
            context_type=context_type,
            status=status
        ).inc()

        if latency_seconds is not None:
            RAG_LLM_LATENCY.labels(
                model=model,
                context_type=context_type
            ).observe(latency_seconds)

        if tokens_input is not None:
            RAG_LLM_TOKENS_INPUT.labels(model=model).inc(tokens_input)

        if tokens_output is not None:
            RAG_LLM_TOKENS_OUTPUT.labels(model=model).inc(tokens_output)

    # -------------------------------------------------------------------------
    # Customer Card Metriken
    # -------------------------------------------------------------------------

    def record_customer_card_lookup(
        self,
        source: str,  # cache, database, generated
        status: str = "success",
        generation_time_seconds: Optional[float] = None
    ):
        """Zeichnet Customer Card Lookup auf."""
        if not self._enabled:
            return

        RAG_CUSTOMER_CARD_LOOKUPS.labels(
            source=source,
            status=status
        ).inc()

        if generation_time_seconds is not None and source == "generated":
            RAG_CUSTOMER_CARD_GENERATION_LATENCY.observe(generation_time_seconds)

    def record_customer_card_sync(self, duration_seconds: float):
        """Zeichnet Customer Card Sync auf."""
        if not self._enabled:
            return

        RAG_CUSTOMER_CARD_SYNC_DURATION.observe(duration_seconds)

    # -------------------------------------------------------------------------
    # Chunking Metriken
    # -------------------------------------------------------------------------

    def record_chunking_request(
        self,
        strategy: str,
        status: str = "success",
        latency_seconds: Optional[float] = None,
        chunks_created: Optional[int] = None,
        avg_chunk_tokens: Optional[float] = None
    ):
        """Zeichnet Chunking Request auf."""
        if not self._enabled:
            return

        RAG_CHUNKING_REQUESTS.labels(
            strategy=strategy,
            status=status
        ).inc()

        if latency_seconds is not None:
            RAG_CHUNKING_LATENCY.labels(
                strategy=strategy
            ).observe(latency_seconds)

    def record_chunk_created(
        self,
        strategy: str,
        section_type: str,
        token_count: int
    ):
        """Zeichnet erstellten Chunk auf."""
        if not self._enabled:
            return

        RAG_CHUNKS_CREATED.labels(
            strategy=strategy,
            section_type=section_type
        ).inc()

        RAG_CHUNK_TOKENS.labels(
            strategy=strategy
        ).observe(token_count)

    # -------------------------------------------------------------------------
    # Chat Metriken
    # -------------------------------------------------------------------------

    def record_chat_message(
        self,
        role: str,
        context_type: str
    ):
        """Zeichnet Chat Message auf."""
        if not self._enabled:
            return

        RAG_CHAT_MESSAGES.labels(
            role=role,
            context_type=context_type
        ).inc()

    def set_active_sessions(self, count: int):
        """Setzt Anzahl aktiver Sessions."""
        if not self._enabled:
            return

        RAG_CHAT_SESSIONS.set(count)

    # -------------------------------------------------------------------------
    # Batch Job Metriken
    # -------------------------------------------------------------------------

    def record_batch_job(
        self,
        job_type: str,
        status: str,
        duration_seconds: Optional[float] = None
    ):
        """Zeichnet Batch Job auf."""
        if not self._enabled:
            return

        RAG_BATCH_JOBS.labels(
            job_type=job_type,
            status=status
        ).inc()

        if duration_seconds is not None:
            RAG_BATCH_JOB_DURATION.labels(
                job_type=job_type
            ).observe(duration_seconds)

    # -------------------------------------------------------------------------
    # Reranker Metriken
    # -------------------------------------------------------------------------

    def record_rerank_request(
        self,
        backend: str,  # gpu, cpu
        status: str = "success",
        latency_seconds: Optional[float] = None,
        documents_count: Optional[int] = None
    ):
        """Zeichnet Reranking Request auf."""
        if not self._enabled:
            return

        RAG_RERANK_REQUESTS.labels(
            backend=backend,
            status=status
        ).inc()

        if latency_seconds is not None:
            RAG_RERANK_LATENCY.labels(
                backend=backend
            ).observe(latency_seconds)

        if documents_count is not None:
            RAG_RERANK_DOCUMENTS.labels(
                backend=backend
            ).observe(documents_count)

    def record_rerank_fallback(self, reason: str):
        """Zeichnet GPU->CPU Fallback auf."""
        if not self._enabled:
            return

        RAG_RERANK_FALLBACKS.labels(reason=reason).inc()

    def set_rerank_model_loaded(
        self,
        backend: str,
        model: str,
        loaded: bool
    ):
        """Setzt Model-Loaded Status."""
        if not self._enabled:
            return

        RAG_RERANK_MODEL_LOADED.labels(
            backend=backend,
            model=model
        ).set(1 if loaded else 0)

    # -------------------------------------------------------------------------
    # System Info
    # -------------------------------------------------------------------------

    def set_system_info(
        self,
        version: str,
        llm_model_realtime: str,
        llm_model_analysis: str,
        embedding_model: str,
        chunk_size: int
    ):
        """Setzt System Info."""
        if not self._enabled:
            return

        RAG_INFO.info({
            "version": version,
            "llm_model_realtime": llm_model_realtime,
            "llm_model_analysis": llm_model_analysis,
            "embedding_model": embedding_model,
            "chunk_size": str(chunk_size)
        })


# Singleton
_metrics_service: Optional[RAGMetricsService] = None


def get_rag_metrics_service() -> RAGMetricsService:
    """Gibt RAGMetricsService Singleton zurueck."""
    global _metrics_service
    if _metrics_service is None:
        _metrics_service = RAGMetricsService()
    return _metrics_service


# =============================================================================
# Convenience Functions
# =============================================================================

def record_search(
    search_type: str,
    latency_ms: int,
    result_count: int,
    status: str = "success"
):
    """Convenience: Search aufzeichnen."""
    get_rag_metrics_service().record_search_request(
        search_type=search_type,
        status=status,
        latency_seconds=latency_ms / 1000,
        result_count=result_count
    )


def record_llm(
    model: str,
    context_type: str,
    latency_ms: int,
    tokens_in: int,
    tokens_out: int,
    status: str = "success"
):
    """Convenience: LLM Request aufzeichnen."""
    get_rag_metrics_service().record_llm_request(
        model=model,
        context_type=context_type,
        status=status,
        latency_seconds=latency_ms / 1000,
        tokens_input=tokens_in,
        tokens_output=tokens_out
    )


def record_chunking(
    strategy: str,
    latency_ms: int,
    chunks: int,
    status: str = "success"
):
    """Convenience: Chunking aufzeichnen."""
    get_rag_metrics_service().record_chunking_request(
        strategy=strategy,
        status=status,
        latency_seconds=latency_ms / 1000,
        chunks_created=chunks
    )


def record_rerank(
    backend: str,
    latency_ms: float,
    documents_count: int,
    status: str = "success"
):
    """Convenience: Reranking aufzeichnen."""
    get_rag_metrics_service().record_rerank_request(
        backend=backend,
        status=status,
        latency_seconds=latency_ms / 1000,
        documents_count=documents_count
    )


def record_rerank_fallback(reason: str):
    """Convenience: Reranker Fallback aufzeichnen."""
    get_rag_metrics_service().record_rerank_fallback(reason=reason)
